repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: mixed-line-ending
  - id: end-of-file-fixer
  - id: check-json
  - id: pretty-format-json
    args: ["--no-sort-keys"]

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  -   id: black

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
